// Curated allowlist of genuinely-searched exam comparisons.
//
// The /compare/[pair] route auto-generates every pairwise combination of TIER1
// exams within a country (~94 pages), but most are combinatorial filler with no
// real search demand (Law vs Medicine, MBA vs Lectureship, Civil-services vs
// Engineering-entrance). Those dilute AdSense content quality. Only the pairs
// below are indexed and listed on /compare/; the rest serve noindex and are
// dropped from the listing. Every page still resolves (HTTP 200) for anyone
// arriving via a direct link.
//
// Keys are the two examIds sorted alphabetically and joined with '|', so the
// order the pair is generated in never matters.

const ALLOW = [
  // Medical (India)
  'aiims-mbbs|neet', 'neet|neet-pg', 'aiims-mbbs|neet-pg',
  // Engineering (India)
  'jeeadvanced|jeemain', 'bitsat|jeemain', 'gate|jeemain',
  'bitsat|jeeadvanced', 'gate|jeeadvanced', 'bitsat|gate',
  // Govt / civil services (India)
  'ssc-cgl|upsc',
  // Famous cross-field "which path should I take" decisions
  'jeemain|neet', 'jeeadvanced|neet', 'cuet|jeemain', 'cuet|neet', 'cuet|jeeadvanced',
  // Engineering-graduate career trilemma (M.Tech vs MBA vs civil services)
  'cat|gate', 'gate|upsc', 'cat|upsc',
  // Pakistan medical-vs-engineering (the local NEET-vs-JEE)
  'ecat|mdcat',
  // Nigeria — all four are university/secondary entrance, mutually comparable
  'jamb|waec', 'jamb|neco', 'jamb|nabteb', 'neco|waec', 'nabteb|waec', 'nabteb|neco',
];

export const COMPARE_INDEX_ALLOWLIST = new Set(
  ALLOW.map((k) => k.split('|').sort().join('|')),
);

export function isCuratedComparePair(idA: string, idB: string): boolean {
  return COMPARE_INDEX_ALLOWLIST.has([idA, idB].sort().join('|'));
}

// Tier-1 exam ids. /compare/[pair] only generates pairs when BOTH exams are in
// this set and share a country (see src/pages/compare/[pair].astro). Exported so
// the exam hub can compute its own comparison partners from the same rule the
// route uses — duplicating the list is how the two would silently drift apart.
export const COMPARE_TIER1 = new Set([
  'neet','jeemain','jeeadvanced','upsc','gate','cuet','ssc-cgl','cat','clat','bitsat',
  'aiims-mbbs','neet-pg','ugc-net','ndab','mdcat','ecat','nat-i','lat','hat-ug',
  'jamb','waec','neco','nabteb',
]);

// Comparison pages this exam can legitimately link to: same country, both tier-1,
// and on the curated allowlist. The allowlist filter is load-bearing — the route
// marks every other pair `noindex,follow`, and an indexed hub must not link into
// a noindexed page.
//
// `slug` is computed with the SAME rule the route uses: pairs are generated by
// walking the country's tier-1 exams in ALL_EXAMS order and emitting
// `${a.examId}-vs-${b.examId}` for i < j. The order is therefore NOT alphabetical
// (the live sitemap has /compare/neet-vs-aiims-mbbs/, not aiims-mbbs-vs-neet), so
// sorting the ids here would emit links to URLs that do not exist.
export function curatedComparePartners(
  examId: string,
  country: string,
  exams: Array<{ examId?: string; examName?: string; country?: string }>,
): Array<{ examId: string; examName: string; slug: string }> {
  if (!examId || !COMPARE_TIER1.has(examId)) return [];
  const inCountry = exams.filter((e) => e && e.examId && e.country === country && COMPARE_TIER1.has(e.examId));
  const self = inCountry.findIndex((e) => e.examId === examId);
  if (self < 0) return [];
  const out: Array<{ examId: string; examName: string; slug: string }> = [];
  for (let j = 0; j < inCountry.length; j++) {
    if (j === self) continue;
    const other = inCountry[j];
    if (!isCuratedComparePair(examId, other.examId as string)) continue;
    const a = j < self ? other : inCountry[self];
    const b = j < self ? inCountry[self] : other;
    out.push({
      examId: other.examId as string,
      examName: other.examName || (other.examId as string),
      slug: `${a.examId}-vs-${b.examId}`,
    });
  }
  return out.sort((x, y) => x.examName.localeCompare(y.examName));
}
